package oop.labor03.lab3_extra.enums;

public enum Department {
    APPLIED_LINGUISTICS,
    APPLIED_SOCIAL_SCIENCE,
    ELECTRICAL_ENGINEERING,
    HORTICULTURE,
    MATHEMATICS_INFORMATICS,
    MECHANICAL_ENGINEERING
}